// auto-doc.cjs — Code-Wiki-style doc generator for toshi/.
// Two passes: structural (deterministic, no LLM) then writes per-file skeletons.
// Run: node scripts/auto-doc.cjs
// Idempotent — re-running overwrites docs/ without duplicating.
const fs = require("fs"), path = require("path"), crypto = require("crypto");
const { execSync } = require("child_process");

const ROOT = path.resolve(__dirname, "..");
const DOCS = path.join(ROOT, "docs");
const EXT_RE = /\.(mjs|cjs|js|jsx|ts|tsx|html|css)$/;
const EXCLUDE = /node_modules|\.git[\\\/]|dist|build|coverage|\.graph|\.toshi|\.claude|\.cbm/;

let files = [];
try {
  files = execSync(`git -C "${ROOT}" ls-files`, { encoding: "utf8" })
    .split("\n").filter(Boolean)
    .filter(f => EXT_RE.test(f) && !EXCLUDE.test(f));
} catch { process.exit(1); }

// ensure dirs
fs.rmSync(DOCS, { recursive: true, force: true });
fs.mkdirSync(path.join(DOCS, "files"), { recursive: true });

// helpers
const read = (rel) => { try { return fs.readFileSync(path.join(ROOT, rel), "utf8"); } catch { return ""; } };
const sha  = (s) => crypto.createHash("sha256").update(s).digest("hex");
const loc  = (s) => s.split("\n").length;
const importPattern = /^(?:\s*import\b[^'";\n]*['"]([^'"]+)['"]|\s*(?:const|let|var)\s+\w+\s*=\s*require\(\s*['"]([^'"]+)['"])/gm;
const exportPattern = /^(?:\s*export\s+(?:default\s+)?(?:async\s+)?(?:function|const|class|let|var)\s+([A-Za-z_$][\w$]*)|^\s*module\.exports\s*=\s*\{?([^=;\n]+)\}?)/gm;

// ── structural pass ────────────────────────────────────────────────────────────
const fileData = [];
for (const rel of files) {
  const src = read(rel);
  if (!src) continue;

  const imports = [...src.matchAll(importPattern)].map(m => m[1] || m[2]).filter(Boolean);
  const exports = [];
  for (const m of src.matchAll(/^\s*export\s+(?:default\s+)?(?:async\s+)?(?:function|const|class|let|var)\s+([A-Za-z_$][\w$]*)/gm)) {
    exports.push(m[1]);
  }
  // reverse-imports: who imports this file's basename?
  const base = path.basename(rel).replace(/\.[^.]+$/, "");
  const usedBy = files.filter(f => {
    if (f === rel) return false;
    const s = read(f);
    return s.includes(`'./${base}'`) || s.includes(`'../${base}'`) || s.includes(`/${base}'`);
  });

  // role: from first comment block (// or /* */) on the first ~25 lines
  const head = src.split("\n").slice(0, 25);
  const comments = [];
  let inBlock = false;
  for (const l of head) {
    const t = l.trim();
    if (inBlock) { comments.push(t.replace(/\*\/$/, "").replace(/^\*+\s?/, "")); if (t.includes("*/")) inBlock = false; continue; }
    if (t.startsWith("//")) comments.push(t.replace(/^\/+\s*/, ""));
    else if (t.startsWith("/*")) { comments.push(t.replace(/^\/\*+\s*/, "")); if (!t.includes("*/")) inBlock = true; }
    else if (comments.length) break;
  }
  const firstReal = src.split("\n").find(l => l.trim() && !l.trim().startsWith("//") && !l.trim().startsWith("*") && !l.trim().startsWith("/*")) || "";
  const role = (comments.join(" ").replace(/\s+/g, " ").trim()
    || firstReal.replace(/^\/\/+\s*/, "").replace(/^#\s*/, "").trim()
    || "(no role inferred)").slice(0, 160);

  const isConfig = /\.(json|ya?ml|toml)$|^\.env|tsconfig|package\.json/.test(rel) && !rel.endsWith("package.json");
  const isPkg   = rel === "package.json";

  fileData.push({ rel, loc: loc(src), imports, exports, usedBy, role, isConfig, isPkg, sha256: sha(src) });

  // per-file doc
  let md = `# \`${rel}\`\n\n`;
  md += `**Role**: ${role}\n`;
  md += `**LOC**: ${loc(src)}\n`;
  md += `**Imports**: ${imports.length ? imports.join(", ") : "none"}\n`;
  if (isPkg) {
    md += `\n## Top-level keys\n`;
    try { md += "```json\n" + JSON.stringify(JSON.parse(src), null, 2).split("\n").slice(0, 25).join("\n") + "\n```\n"; } catch {}
  } else if (exports.length) {
    md += `\n**Exports**:\n\n| Name | Kind |\n|---|---|\n`;
    for (const e of exports) md += `| \`${e}\` | export |\n`;
  }
  md += `\n## Used by\n`;
  md += usedBy.length ? usedBy.map(f => `- \`${f}\``).join("\n") : "_leaf — not imported_";
  md += `\n`;

  fs.writeFileSync(path.join(DOCS, "files", rel.replace(/[\\\/]/g, "__") + ".md"), md);
}

// ── INDEX.md (one screen) ─────────────────────────────────────────────────────
let idx = `# toshi — auto-generated wiki\n\n`;
idx += `> Generated by \`scripts/auto-doc.cjs\` on ${new Date().toISOString()}. Re-run to refresh.\n\n`;
idx += `## What it is\nA floating terminal companion: a tiny AI mascot (Toshi) that lives in a transparent, always-on-top window beside your terminal and answers grounded questions about your current session via an MCP server.\n\n`;
idx += `## Shape\n`;
const groups = { "mcp/": [], "lib/": [], "panel/": [], "desktop/": [], "tools/": [], "scripts/": [], "test/": [], "(root)": [] };
for (const f of fileData) {
  const key = Object.keys(groups).find(g => f.rel.startsWith(g) && g !== "(root)") || "(root)";
  groups[key].push(f);
}
for (const [g, arr] of Object.entries(groups)) if (arr.length) idx += `- ${g.padEnd(10)} ${arr.length} files\n`;
idx += `\n## Spine (do not break casually)\n1. \`lib/session.mjs\` — session knowledge (ask/status/setRepo); consumed by mcp + tools\n2. \`lib/llm.mjs\` — chat + grounded speak()\n3. \`mcp/toshi-mcp.mjs\` — stdio MCP server (toshi_status/ask/mood/watch) + /ask bridge\n4. \`desktop/main.cjs\` — Electron entry; spawns the brain\n5. \`panel/index.html\` — the only UI; talks to brain over :4820\n6. \`serve.js\` — static panel server on :4821 (browser-only dev)\n\n`;
idx += `## How to run it\n- install: \`npm install\`\n- run face: \`npm run toshi\` (Electron floating window + brain)\n- run brain: \`npm run brain\` (stdio MCP server only)\n- ask CLI: \`npm run ask\`\n- test: \`npm test\`\n\n`;
idx += `## How to make a safe first change\n- Pick a leaf in \`test/\`; run \`npm test\` first.\n- Tweak a cosmetic in \`panel/index.html\` (CSS, lines 16–50).\n- Avoid \`lib/session.mjs\` and \`mcp/toshi-mcp.mjs\` until you know which of the 5 callers you'll break.\n`;
fs.writeFileSync(path.join(DOCS, "INDEX.md"), idx);

// ── graph.md (Mermaid) ────────────────────────────────────────────────────────
let g = `# Dependency spine\n\n\`\`\`mermaid\ngraph LR\n  brain[mcp/toshi-mcp.mjs] --> session[lib/session.mjs]\n  brain --> llm[lib/llm.mjs]\n  brain --> tts[lib/tts.mjs]\n  plugin[tools/toshi.mjs] --> session\n  desktop[desktop/main.cjs] --> brain\n  panel[panel/index.html] -.HTTP /ask.-> brain\n  serve[serve.js] --> panel\n  cli[bin/toshi.cjs] --> llm\n\`\`\`\n\n## Top imported local modules (from .graph/)\n\n| Local module | Importers |\n|---|---|\n| llm.mjs | 8 |\n| session.mjs | 5 |\n| tts.mjs | 2 |\n`;
fs.writeFileSync(path.join(DOCS, "graph.md"), g);

// ── _manifest.json (drift check) ──────────────────────────────────────────────
const manifest = {
  generated_at: new Date().toISOString(),
  target: ROOT,
  files: fileData.map(f => ({ path: f.rel, loc: f.loc, doc: "docs/files/" + f.rel.replace(/[\\\/]/g, "__") + ".md", sha256: f.sha256 })),
  index: "docs/INDEX.md",
};
fs.writeFileSync(path.join(DOCS, "_manifest.json"), JSON.stringify(manifest, null, 2));

console.log(`docs: ${fileData.length} per-file pages + INDEX.md + graph.md + _manifest.json`);
